[tool.black]
line-length = 93

[tool.pycln]
all = true

[tool.isort]
line_length = 93
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
